### Spring properties
# Service registers under this name
spring:
  application:
    name: ix-data-matching

# Discovery Server Access
#eureka:
#    client:
#      serviceUrl:
#        defaultZone: http://localhost:1111/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 2023
  error:
    whitelabel:
      enabled: false
